#!/bin/bash

set -e

#-exclude_subjs 10662,10711,11246,11279,11318

defaults=$(cat <<_EOF_
 -statbrik_dir /Volumes/Serena/MMClock/clock_3dmema/glm_stat_files -statbrik_suffix _glm_hrf_clock_preconvolve_valueModel_emoint_normalized_stats_REML+tlrc
 -cov_file /Volumes/Serena/MMClock/clock_3dmema/memacov_ageexplore.txt -missing_data 0 -max_zeros 0.2
 -mask ~/standard/mni_icbm152_nlin_asym_09c/mni_icbm152_t1_tal_nlin_asym_09c_mask_2.3mm.nii
 -model_outliers -jobs 14 -covariates_center mean -covariates_model center=different slope=different -HKtest -residual_Z
_EOF_
)

for contrast in m_ev_overall \
    m_rpe_neg_overall \
    m_rpe_pos_overall \
    m_rel_uncertainty_overall \
    m_mean_uncertainty_overall \
    ev_fear_gt_scram ev_happy_gt_scram ev_fear_gt_happy \
    rpe_neg_fear_gt_scram rpe_neg_happy_gt_scram rpe_neg_fear_gt_happy \
    rpe_pos_fear_gt_scram rpe_pos_happy_gt_scram rpe_pos_fear_gt_happy \
    rel_uncertainty_fear_gt_scram rel_uncertainty_happy_gt_scram rel_uncertainty_fear_gt_happy \
    mean_uncertainty_fear_gt_scram mean_uncertainty_happy_gt_scram mean_uncertainty_fear_gt_happy
do
    setup3dMEMA -glm_contrast $contrast $defaults -covs subj -run
    setup3dMEMA -glm_contrast $contrast $defaults -covs subj,age.c,female.c -run
    setup3dMEMA -glm_contrast $contrast $defaults -covs subj,age.c,female.c,alpha_diff.c -run
    setup3dMEMA -glm_contrast $contrast $defaults -covs subj,female.c,age.c,explorer,exp_age.c -run
done

#setup3dMEMA -glm_contrast $contrast $defaults -covs subj,age.c -run
#setup3dMEMA -glm_contrast $contrast $defaults -covs subj,adult -run
#setup3dMEMA -glm_contrast $contrast $defaults -covs subj,adult,female -run

#removed here for speed
#m_ev_scram m_ev_happy m_ev_fear
#m_rpe_neg_scram m_rpe_neg_happy m_rpe_neg_fear 
#m_rpe_pos_scram m_rpe_pos_happy m_rpe_pos_fear
